### ISSUE TITLE
map through multiple inputs

### ISSUE THREAD

**Issue by raphaelchinchilla** [mcabbott/SliceMap.jl#13]
First, I have to say that I love this package, and I have been [looking for something like this for a while](https://discourse.julialang.org/t/getting-non-vectorized-code-to-the-speed-of-vectorized-ones/71525). I am submitting two issues that I would love to contribute to in order to improve the package.

I was wondering how hard it would be to modify `mapcols` such that it maps through multiple inputs (the same way that map does). This would be a breaking change because `mapcols(f, M, args...)` is currently equivalent to `map(col -> _vec(f(col, args...)), eachcol(M))`, but the feature would not be lost as the user could always just do `mapcols(x->f(x,args...),M)`

**Comment by mcabbott** [comment]
Glad if it's useful! It solved something I needed but hasn't seen much work since. 

One difficulty with extending these functions to multiple arrays is that you may not want to slice them all the same way. My current view is that the right tool is probably something which looks a little different:
* I hope that https://github.com/JuliaLang/julia/pull/43334 will be merged, which allows things like `stack(f, eachcol(A), eachrow(B))`. (It would need gradient rules, which `eachcol` etc. already have.)
* Another explicit way is to use TensorCast, which understands things like `@cast C[k,i] := f(A[:,i], B[i,:])[k]`. Opinions vary about whether this is readable or ugly.

**Comment by raphaelchinchilla** [comment]
I hope that it does get merged too. For me it always seemed that if `map` can take multiple inputs, `mapslices` (or `slicemap`) should also. 

FWIW, it is a bit frustrating that Julia has the `broadcast` function that works so well for functions taking scalar inputs, but does not have the same technology for functions taking Array inputs. But also, I never understood what is the difference between `map` and `broadcast` as `broadcast(f,eachcol(x))` and `map(f,eachcol(x))` both return the same value in basically the same amount of time.

**Comment by mcabbott** [comment]
For one argument, there is seldom a difference between map & broadcast. But for two, `map(+, [1,2], [4 5 6])` is a zip (though I wish it were an error, like `map(+, [1;2;;], [4 5 6])` is) while `broadcast(+, [1,2], [4 5 6])` extends shapes. It does seem a little redundant, not so sure how this was arrived at.

**Comment by raphaelchinchilla** [comment]
> wish it were an error

it is very disturbing that this is not an error
